apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 049725296147.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 049725296147.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 58aad1c1
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
